;;; sxhkdrc-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from sxhkdrc-mode.el

(autoload 'sxhkdrc-mode "sxhkdrc-mode" "\
Major mode for editing sxhkdrc files (Simple X Hot Key Daemon).

(fn)" t)
(add-to-list 'auto-mode-alist '("sxhkdrc\\'" . sxhkdrc-mode))
(register-definition-prefixes "sxhkdrc-mode" '("sxhkdrc-"))

;;; End of scraped data

(provide 'sxhkdrc-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; sxhkdrc-mode-autoloads.el ends here
